In [453]:
import numpy as np
import pandas as pd
import matplotlib as mp
import seaborn as sb
from numpy.linalg import inv

In [396]:
pd.__version__


'1.5.3'

In [397]:
datalink = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv'

In [398]:
datalink

'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv'

In [399]:
df_house = pd.read_csv(datalink)

In [400]:
df_house.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY

In [401]:
df_house.loc[0].count()

10

In [402]:
df_house.isnull().sum()


longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [403]:
df_house['ocean_proximity']

0        NEAR BAY
1        NEAR BAY
2        NEAR BAY
3        NEAR BAY
4        NEAR BAY
           ...   
20635      INLAND
20636      INLAND
20637      INLAND
20638      INLAND
20639      INLAND
Name: ocean_proximity, Length: 20640, dtype: object

In [404]:
df_house['ocean_proximity'].count()

20640

In [405]:
df_house.groupby('ocean_proximity')

In [406]:
df_house['ocean_proximity'].nunique()

5

In [407]:
df_house.ocean_proximity.value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

In [408]:
df_house.groupby('ocean_proximity').median_house_value.mean().round(0)

ocean_proximity
<1H OCEAN     240084.0
INLAND        124805.0
ISLAND        380440.0
NEAR BAY      259212.0
NEAR OCEAN    249434.0
Name: median_house_value, dtype: float64

In [409]:
df_house.head(1)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY

In [410]:
df_house.total_bedrooms

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...  
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64

In [492]:
df_house.total_bedrooms.shape[0]

20640

In [493]:
df_house.total_bedrooms.mean().round(3)

537.871

In [494]:
def index_nan(v):
    n=v.shape[0]
    result=False
    for i in range (n):
        if np.isnan(v[i]):
            return i
    return i


In [495]:
index_nan(df_house.total_bedrooms)

290

In [496]:
b=np.array(df_house.total_bedrooms)

In [497]:


a=df_house.total_bedrooms[290]
a

nan

In [498]:
df_house.total_bedrooms.isnull().sum()

207

In [499]:
def replace_nan(v,num):
    n=v.shape[0]
    for i in range (n):
        if np.isnan(v[i]):
            v[i]=num
    return v

In [500]:
replace_nan(b,537.871)

array([ 129., 1106.,  190., ...,  485.,  409.,  616.])

In [501]:
b[290]

537.871

In [502]:
b.mean()

537.8705570251938

In [504]:
b.mean().round(3)

537.871

In [423]:
c=pd.DataFrame(df_house.total_bedrooms)
c

total_bedrooms
0               129.0
1              1106.0
2               190.0
3               235.0
4               280.0
...               ...
20635           374.0
20636           150.0
20637           485.0
20638           409.0
20639           616.0

[20640 rows x 1 columns]

In [424]:
c.total_bedrooms[290]

nan

In [425]:
cclean=c.fillna(538)

In [426]:
cclean

total_bedrooms
0               129.0
1              1106.0
2               190.0
3               235.0
4               280.0
...               ...
20635           374.0
20636           150.0
20637           485.0
20638           409.0
20639           616.0

[20640 rows x 1 columns]

In [427]:
cclean.total_bedrooms[290]

538.0

In [428]:
cclean.total_bedrooms.mean()

537.8718507751938

In [429]:
cclean.total_bedrooms.mean().round(0)

538.0

In [430]:
df_house.groupby('ocean_proximity').median_house_value.mean().round(0)

ocean_proximity
<1H OCEAN     240084.0
INLAND        124805.0
ISLAND        380440.0
NEAR BAY      259212.0
NEAR OCEAN    249434.0
Name: median_house_value, dtype: float64

In [431]:
df_esercizio7 = pd.DataFrame(df_house[["housing_median_age", "total_rooms", "total_bedrooms","ocean_proximity"]])
df_esercizio7

housing_median_age  total_rooms  total_bedrooms ocean_proximity
0                    41.0        880.0           129.0        NEAR BAY
1                    21.0       7099.0          1106.0        NEAR BAY
2                    52.0       1467.0           190.0        NEAR BAY
3                    52.0       1274.0           235.0        NEAR BAY
4                    52.0       1627.0           280.0        NEAR BAY
...                   ...          ...             ...             ...
20635                25.0       1665.0           374.0          INLAND
20636                18.0        697.0           150.0          INLAND
20637                17.0       2254.0           485.0          INLAND
20638                18.0       1860.0           409.0          INLAND
20639                16.0       2785.0           616.0          INLAND

[20640 rows x 4 columns]

In [432]:
df_esercizio7[df_esercizio7["ocean_proximity"]=='ISLAND']

housing_median_age  total_rooms  total_bedrooms ocean_proximity
8314                27.0       1675.0           521.0          ISLAND
8315                52.0       2359.0           591.0          ISLAND
8316                52.0       2127.0           512.0          ISLAND
8317                52.0        996.0           264.0          ISLAND
8318                29.0        716.0           214.0          ISLAND

In [433]:
X = np.array(df_esercizio7[df_esercizio7["ocean_proximity"]=='ISLAND'])

In [434]:
X.shape

(5, 4)

In [435]:
X=np.delete(X,3,1)
X

array([[27.0, 1675.0, 521.0],
       [52.0, 2359.0, 591.0],
       [52.0, 2127.0, 512.0],
       [52.0, 996.0, 264.0],
       [29.0, 716.0, 214.0]], dtype=object)

In [436]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1]==V.shape[0]
    num_rows=U.shape[0]
    num_cols=V.shape[1]
    result=np.zeros((num_rows, num_cols))
    
    for i in range (num_cols):
           result[:,i]=matrix_vector_multiplication(U,V[:,i])
    return result


In [437]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1]==v.shape[0]
    
    num_rows=U.shape[0]
    
    result=np.zeros(num_rows)
    
    for i in range (num_rows):
           result[i]=vector_vector_multiplication(U[i],v)
    return result
    
    

In [438]:
def vector_vector_multiplication(u,v):
    assert u.shape[0]==v.shape[0]
    n=u.shape[0]
    result=0
    for i in range (n):
        result=result+u[i]*v[i]
        
    return result

In [439]:
X.shape

(5, 3)

In [462]:
Xt=np.array(X.T)
Xt.astype(int)

array([[  27,   52,   52,   52,   29],
       [1675, 2359, 2127,  996,  716],
       [ 521,  591,  512,  264,  214]])

In [463]:
Xt.shape

(3, 5)

In [465]:
XTX=np.array(Xt.dot(X))
XTX.astype(int)

array([[    9682,   351053,    91357],
       [  351053, 14399307,  3772036],
       [   91357,  3772036,   998358]])

In [466]:
XTX.shape

(3, 3)

In [467]:
y=np.array([[950, 1300, 800, 1000, 1300]])
y

array([[ 950, 1300,  800, 1000, 1300]])

In [479]:
XTX

array([[9682.0, 351053.0, 91357.0],
       [351053.0, 14399307.0, 3772036.0],
       [91357.0, 3772036.0, 998358.0]], dtype=object)

In [482]:
XTXinv=np.linalg.inv(XTX.astype(int))
XTXinv


array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [483]:
XTXinv.shape

(3, 3)

In [373]:
XTX.shape

(5, 5)

In [369]:
Xt.shape

(3, 5)

In [484]:
wa=np.array(matrix_matrix_multiplication(XTXinv,Xt))
wa

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [486]:
wa.shape

(3, 5)

In [487]:
y.T

array([[ 950],
       [1300],
       [ 800],
       [1000],
       [1300]])

In [488]:
w=np.array(matrix_vector_multiplication(wa,y.T))
w

array([23.12330961, -1.48124183,  5.69922946])